server:
  servlet:
    context-path: /api/v1
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/lesson-db
    driver-class-name: com.mysql.cj.jdbc.Driver
